#Do you want to receive automatic updates?
auto-update: true

#MySQL (Optional but required if you're using this badboy for multi-server setups ie. BungeeCord)
MySQL:
  Enabled: false
  Username: user
  Password: password
  Ip: 0.0.0.0
  Database: tatemylove_rocks

#Time until the game starts in seconds (From lobby)
time-to-start: 20

#The time each games lasts in seconds
game-time: 600

#Minimum players to start
min-players: 2

#Enabled this if you are using COD for multi-servers
BungeeCord:
  #Enabling this will also enable auto-join
  enabled: false
  #Where should players be sent when the game ends?
  fall-back: hub

#Using economy with COD requires swift economy https://www.spigotmc.org/resources/swift-economy-mysql-api.50208/ (Optional)
SwiftEconomy:
  enabled: false

#Use protocolLib (Requires protocolLib https://www.spigotmc.org/resources/protocollib.1997/) for cooler messages (Optional)
protocolLib:
  enabled: false

#Use Citizens2 (Requires citizens2 https://ci.citizensnpcs.co/job/Citizens2/) for NPC's (Optional)
Citizens2:
  enabled: false
